# Generated by Django 5.2.9 on 2026-01-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Accidentes'), ('V', 'Vialidad'), ('U', 'Urbanidad')], max_length=1)),
                ('severity', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Abierto'), ('E', 'En proceso'), ('C', 'Cerrado')], default='A', max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
